env:
   global:
     - CONAN_REFERENCE: "flann/1.9.1"
     - CONAN_LOGIN_USERNAME: "admin"
     - CONAN_UPLOAD: "http://cytosplore.lumc.nl:8081/artifactory/api/conan/conan-local"
#     - CONAN_STABLE_BRANCH_PATTERN: "release/*"
#     - CONAN_UPLOAD_ONLY_WHEN_STABLE: 1 # Will only upload when the branch matches "release/*"
     
linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:

      - <<: *linux
        env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc5 CONAN_BUILD_TYPES=Release
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=8 CONAN_DOCKER_IMAGE=conanio/gcc5 CONAN_BUILD_TYPES=Debug
      - <<: *osx
        osx_image: xcode10.3
        env: CONAN_APPLE_CLANG_VERSIONS=10.0 CONAN_BUILD_TYPES=Release CONAN_ARCHS=x86_64 CONAN_IS_TRAVIS_OSX=1  
      - <<: *osx
        osx_image: xcode10.3
        env: CONAN_APPLE_CLANG_VERSIONS=10.0 CONAN_BUILD_TYPES=Debug CONAN_ARCHS=x86_64 CONAN_IS_TRAVIS_OSX=1         


install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
